// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzyaeaiisbwrckthenzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6eWFlYWlpc2J3cmNrdGhlbnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQ1NDQsImV4cCI6MjA2ODY3MDU0NH0.rz3CzOU6Wbx6RQy9VLQTyEA7P54agxU2nkvZcIofEuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});